package main

import (
	"encoding/json"
	"fmt"
)

type AutoGenerated struct {
	Age   int    `json:"age"`
	Name  string `json:"name"`
	Child []int  `json:"child"`
}

//av:=a.Child 属于值传递。后续更新对象并不会影响av
//关于对象的数学，大写开头的才可以访问和复制。
func Test1Main() {
	jsonStr1 := `{"age": 14,"name": "potter", "child":[1,2,3]}`
	a := AutoGenerated{}
	json.Unmarshal([]byte(jsonStr1), &a)

	av := a.Child
	fmt.Printf("1 av:%v \n", av)

	jsonStr2 := `{"age": 14,"name": "potter", "child":[1,2,3,23,21,32,3]}`
	json.Unmarshal([]byte(jsonStr2), &a)

	fmt.Printf("2 av:%v \n", av)

}
